              - name: HCL AppScan CodeSweep
                uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
            

on:
  push:
    branches:
      - main

jobs:
  appscan-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AppScan
        uses: HCLAppScan/appscan-github-action@v2
        with:
          appscan-version: 12.9.1
          license-key: ${{ secrets.APPSCAN_LICENSE_KEY }}
          appscan-server-url: https://your-appscan-server-url
          appscan-service: default

      - name: Scan application
        run: |
          appscan scan -t scan -a your-application.zip

      - name: Upload scan results
        uses: actions/upload-artifact@v2
        with:
          name: appscan-scan-results
          path: /path/to/scan-results.zip # Adjust the path based on your AppScan scan output
