name: Checkmarx IAST

on:
  push:
    branches:
      - main

jobs:
  iast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Checkmarx IAST Agent
        run: |
          curl -s https://download.checkmarx.com/iast/agent/latest/checkmarx-iast-agent_linux_x64.tar.gz | tar xzf -
          sudo ./checkmarx-iast-agent install

      - name: Configure Checkmarx IAST
        run: |
          cat << EOF > /opt/checkmarx/iast/agent.conf
          {
            "server": {
              "url": "https://your-checkmarx-iast-server-url",
              "token": "${{ secrets.CHECKMARX_IAST_API_TOKEN }}"
            }
          }
          EOF

      - name: Start Checkmarx IAST Agent
        run: |
          sudo ./checkmarx-iast-agent start

      - name: Run Checkmarx IAST Scan
        run: |
          sudo ./checkmarx-iast-agent scan

      - name: Upload Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: checkmarx-iast-scan-results
          path: /opt/checkmarx/iast/results/latest
