on:
  push:
    branches:
      - main
      
jobs:
  contrast-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Contrast Security CLI
      run: |
        npm install -g @contrast/cli

    - name: Run Contrast Security Scan
      run: |
        contrast security scan \
          --username ${{ secrets.CONTRAST_USERNAME }} \
          --api-key ${{ secrets.CONTRAST_API_KEY }} \
          --org-id ${{ secrets.CONTRAST_ORG_ID }} \
          --app-name YourAppName \
          --auto-open

    # Add additional steps as needed

